// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addCommentBtn': string;
  'commentAvatar': string;
  'commentContent': string;
  'commentListContainer': string;
  'commentUserInfo': string;
  'commentWrapper': string;
  'count': string;
  'countInfo': string;
  'defaultAvatar': string;
  'discussContainer': string;
  'header': string;
  'headerAvatar': string;
  'replyBtn': string;
  'replyTextArea': string;
  'user': string;
  'userSelectIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
