// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'loginContainer': string;
  'loginForm': string;
  'loginIcon': string;
  'logoIcon': string;
}
export const cssExports: CssExports;
export default cssExports;
