// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'articleManager': string;
  'dataList': string;
  'editor': string;
  'filter': string;
  'footer': string;
  'label': string;
  'operation': string;
  'operationItem': string;
  'searchItem': string;
  'tag': string;
  'updateArticle': string;
}
export const cssExports: CssExports;
export default cssExports;
