// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'tagItem': string;
  'tagsWrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
