// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'antion': string;
  'appContainer': string;
  'blogName': string;
  'contentLayout': string;
  'headLeft': string;
  'headNav': string;
  'headerAvatar': string;
  'headerContainer': string;
  'headerSearch': string;
  'headerUserInfo': string;
  'mainWrapper': string;
  'menuItem': string;
  'rightCol': string;
  'searchBox': string;
}
export const cssExports: CssExports;
export default cssExports;
