// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'antion': string;
  'appContainer': string;
  'articleItem': string;
  'blogName': string;
  'clickLink': string;
  'contentLayout': string;
  'desc': string;
  'headLeft': string;
  'headNav': string;
  'headerAvatar': string;
  'headerContainer': string;
  'headerSearch': string;
  'headerUserInfo': string;
  'hotArticle': string;
  'link': string;
  'linkIcon': string;
  'linkItem': string;
  'mainWrapper': string;
  'menuItem': string;
  'rightCol': string;
  'searchBox': string;
  'siderAvatar': string;
  'siderBar': string;
  'siderTitle': string;
  'tag': string;
  'tagList': string;
}
export const cssExports: CssExports;
export default cssExports;
