// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'badge': string;
  'header': string;
  'info': string;
  'tagItem': string;
  'tagPage': string;
  'tagsWrapper': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
