// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'dataList': string;
  'filter': string;
  'label': string;
  'operation': string;
  'operationItem': string;
  'searchItem': string;
}
export const cssExports: CssExports;
export default cssExports;
