// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'article': string;
  'articleItem': string;
  'articleList': string;
  'articleListContainer': string;
  'articleListWrapper': string;
  'createTime': string;
  'description': string;
  'empty': string;
  'icon': string;
  'item': string;
  'markdown': string;
  'otherInfo': string;
  'pagination': string;
  'preView': string;
  'previewDivider': string;
  'previewTitle': string;
  'tagContainer': string;
  'tagIcon': string;
  'title': string;
  'viewCountAndDicuss': string;
}
export const cssExports: CssExports;
export default cssExports;
