// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'article': string;
  'articleItem': string;
  'articleList': string;
  'articleListWrapper': string;
  'createTime': string;
  'description': string;
  'markdown': string;
  'pagination': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
