// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'articleAnchor': string;
  'articleDetail': string;
  'content': string;
  'detailContainer': string;
  'detailContent': string;
  'header': string;
  'markdown': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
