// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'createdAt': string;
  'infoWrapper': string;
  'listTitle': string;
  'loading': string;
  'tagWithArticleWrapper': string;
  'timelineWrapper': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
